Homework 03. Работа с сетью и Docker-compose
Temox/microservices pull request #3
Opened 2017-10-22 11:53 UTC by Temox

Работа с сетью в docker-контейнерах:
none driver
host  driver
bridge  driver

Docker-compose. Описание инфраструктуры, для вэб-приложения, в виде кода и запуск с помощью docker-контейнеров.

2017-10-27 21:07 UTC, chromko requested changes
Не вижу примера .env-файла или самого .env-файла. Добавьте, пожалуйста

2017-10-27 21:07 UTC, chromko commented on docker-compose.yml
> +    image: mongo:3.2
версию БД тоже можно вынести в переменные

2017-10-27 21:07 UTC, chromko commented on docker-compose.yml
> +    image: ${USERNAME}/${UI_BUILD}
Нет смысла использовать переменные USERNAME и UI_BUILD вместе. Тогда уже полностью наименование образа забивать в одну переменную.
Но, полагаю, что в вашем случае, лучше вынести в compose из UI_BUILD название образа и оставить в качестве изменяемого параметра только его версию.

2017-11-08 16:06 UTC, Artemmkin commented
ребят, долго висит в ПР и не понятен статус. Там вроде изменений немного нужно внести.

2017-11-13 12:38 UTC, Temox commented
Коллеги, добрый день.
У меня наложились два обучения и на работе завал. Сейчас немного разобрался с загрузкой. Продолжаю делать ДЗ))
Добавил .env-файл, поменял используемые переменные.

2017-12-04 11:03 UTC, chromko approved these changes

2017-12-04 11:04 UTC, chromko commented
конфликт только уберите, пожалуйста. А так все ок

2017-12-04 12:04 UTC, merged